# Generated by Django 3.2.3 on 2021-05-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibremastered', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='view',
            field=models.CharField(default='', help_text='Format: app/template_name.html', max_length=250, null=True),
        ),
    ]
