# Generated by Django 3.2.3 on 2021-05-14 22:33

from django.db import migrations, models
import django.db.models.deletion
import sitetree.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sitetree', '0002_auto_20210514_2145'),
        ('fibremastered', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='display_title',
        ),
        migrations.RemoveField(
            model_name='site',
            name='title_text',
        ),
        migrations.AddField(
            model_name='site',
            name='access_guest',
            field=models.BooleanField(db_index=True, default=False, help_text='Check it to grant access to this item to guests only.', verbose_name='Guests only'),
        ),
        migrations.AddField(
            model_name='site',
            name='access_loggedin',
            field=models.BooleanField(db_index=True, default=False, help_text='Check it to grant access to this item to authenticated users only.', verbose_name='Logged in only'),
        ),
        migrations.AddField(
            model_name='site',
            name='access_perm_type',
            field=models.IntegerField(choices=[(1, 'Any'), (2, 'All')], default=1, help_text='<b>Any</b> &mdash; user should have any of chosen permissions. <b>All</b> &mdash; user should have all chosen permissions.', verbose_name='Permissions interpretation'),
        ),
        migrations.AddField(
            model_name='site',
            name='access_permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='Permissions granting access'),
        ),
        migrations.AddField(
            model_name='site',
            name='access_restricted',
            field=models.BooleanField(db_index=True, default=False, help_text='Check it to restrict user access to this item, using Django permissions system.', verbose_name='Restrict access to permissions'),
        ),
        migrations.AddField(
            model_name='site',
            name='alias',
            field=sitetree.models.CharFieldNullable(blank=True, db_index=True, help_text='Short name to address site tree item from a template.<br /><b>Reserved aliases:</b> "trunk", "this-children", "this-siblings", "this-ancestor-children", "this-parent-siblings".', max_length=80, null=True, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Additional comments on this item.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='site',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether to show this item in navigation.', verbose_name='Hidden'),
        ),
        migrations.AddField(
            model_name='site',
            name='hint',
            field=models.CharField(blank=True, default='', help_text='Some additional information about this item that is used as a hint.', max_length=200, verbose_name='Hint'),
        ),
        migrations.AddField(
            model_name='site',
            name='inbreadcrumbs',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether to show this item in a breadcrumb path.', verbose_name='Show in breadcrumb path'),
        ),
        migrations.AddField(
            model_name='site',
            name='inmenu',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether to show this item in a menu.', verbose_name='Show in menu'),
        ),
        migrations.AddField(
            model_name='site',
            name='insitetree',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether to show this item in a site tree.', verbose_name='Show in site tree'),
        ),
        migrations.AddField(
            model_name='site',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent site tree item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_parent', to='fibremastered.site', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='site',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, help_text='Item position among other site tree items under the same parent.', verbose_name='Sort order'),
        ),
        migrations.AddField(
            model_name='site',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='site',
            name='tree',
            field=models.ForeignKey(default='', help_text='Site tree this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='site_tree', to='sitetree.tree', verbose_name='Site Tree'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='urlaspattern',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the given URL should be treated as a pattern.<br /><b>Note:</b> Refer to Django "URL dispatcher" documentation (e.g. "Naming URL patterns" part).', verbose_name='URL as Pattern'),
        ),
        migrations.AlterField(
            model_name='site',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(default='', max_length=250),
        ),
    ]
