# Generated by Django 3.2.3 on 2021-05-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fibremastered', '0002_site_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='view',
        ),
    ]
