# Generated by Django 3.2.3 on 2021-05-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibremastered', '0003_alter_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
