# Generated by Django 3.2.3 on 2021-05-15 19:50

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fibremastered', '0003_remove_site_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='body',
            field=django_editorjs.fields.EditorJsField(blank=True, null=True),
        ),
    ]
