# Generated by Django 3.2.3 on 2021-05-14 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fibremastered', '0004_auto_20210514_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='transfer_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
