# Generated by Django 3.2.3 on 2021-05-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibremastered', '0005_site_transfer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='displaytitle',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(help_text='Site tree item title. Can contain template variables E.g.: {{ mytitle }}.', max_length=100, verbose_name='Title'),
        ),
    ]
