# Generated by Django 3.2.3 on 2021-05-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fibremastered', '0006_auto_20210514_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='displaytitle',
            new_name='display_title',
        ),
    ]
